--- 
blank_issues_enabled: true
contact_links:
  -
    name: "Documentation"
    about: "Please read the documentation before opening a new issue"
    url: "https://jokeapi.dev/"
  -
    name: "Chat"
    about: "If you have any non-issue-worthy questions, join my Discord server and I'll try to help you"
    url: "https://sv443.net/discord"
