name: build

on: [push] # runs on every push


jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1 # checkout latest commit
    - name: Use Node.js ${{ matrix.node-version }} # set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Clean Install of Dependencies # runs the npm ci command to install all dependencies
      run: |
        npm ci
      env:
        CI: "true"
    # - name: Lint Code # lints the code to find any errors
    #   run: |
    #     npm run lint
    #   env:
    #     CI: "true"
    - name: Validate Joke Files # validates the joke files
      run: |
        npm run validate-jokes
      env:
        CI: "true"
    - name: Validate Joke IDs # makes sure all jokes have the correct ID
      run: |
        npm run validate-ids
      env:
        CI: "true"
    - name: Send Discord Success Notification # sends a Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'âœ… **JokeAPI CI** (triggered by `{{GITHUB_ACTOR}}` on `{{GITHUB_REF}}`) was successful (see https://github.com/Sv443/JokeAPI/commit/{{GITHUB_SHA}}/checks)' 
    - name: Send Discord Failure Notification # sends a Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'ðŸš« **JokeAPI CI** (triggered by `{{GITHUB_ACTOR}}` on `{{GITHUB_REF}}`) has failed (see https://github.com/Sv443/JokeAPI/commit/{{GITHUB_SHA}}/checks)'
      if: failure()
